//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoVoyage.Donnees
{
    using System;
    using System.Collections.Generic;
    
    public partial class DestinationVoyage
    {
        public System.Guid Destination { get; set; }
        public System.Guid Voyage { get; set; }
        public long id { get; set; }
        public string DestinationVoyage1 { get; set; }
    
        public virtual Destination Destination1 { get; set; }
        public virtual Voyage Voyage1 { get; set; }
    }
}
