//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoVoyage.Donnees
{
    using System;
    using System.Collections.Generic;
    
    public partial class DossierVoyageur
    {
        public long id { get; set; }
        public System.Guid Voyageur { get; set; }
        public System.Guid Dossier { get; set; }
    
        public virtual Dossier Dossier1 { get; set; }
        public virtual Voyageur Voyageur1 { get; set; }
    }
}
