//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoVoyage.Donnees
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dossier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dossier()
        {
            this.DossierVoyageurs = new HashSet<DossierVoyageur>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid Voyage { get; set; }
        public System.Guid Client { get; set; }
        public byte Etat { get; set; }
        public Nullable<System.Guid> Assurance { get; set; }
        public Nullable<System.Guid> Commercial { get; set; }
    
        public virtual Assurance Assurance1 { get; set; }
        public virtual Client Client1 { get; set; }
        public virtual Employe Employe { get; set; }
        public virtual Voyage Voyage1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DossierVoyageur> DossierVoyageurs { get; set; }
    }
}
