//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoVoyage.Scenario1.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class LignePanier
    {
        public System.Guid Id { get; set; }
        public byte NombreVoyageur { get; set; }
        public System.Guid VoyageID { get; set; }
        public string PanierID { get; set; }
    
        public virtual Voyage Voyage { get; set; }
    }
}
